import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-center pt-40'>
        <h1 className='text-lime-600 text-4xl '>Home Page</h1>
        <p>click here to go <a className='text-blue-500' href='./about'>about</a> page</p>
      </div>
    </div>
  )
}
